import type { Project } from "./types";
function project(
  id: string,
  utilityId: string,
  utilityName: string,
  name: string,
  type: string,
  longitude: number,
  latitude: number,
  start: string | null,
  end: string | null,
): Project {
  return {
    id,
    utilityId,
    utilityName,
    name,
    type,
    status: "Planned",
    location: { longitude, latitude },
    geometryQuality: "approximate-point",
    constructionStart: start,
    constructionEnd: end,
    inServiceDate: end,
    datePrecision: start ? "day" : "unknown",
    synthetic: true,
    evidence: [
      {
        field: "Location",
        sourceTitle: "Synthetic planning worksheet",
        sourceUrl: null,
        pageOrRow: `Fixture ${id}`,
        quote:
          "An approximate demonstration point in the Miami area. This is not a real project location.",
        synthetic: true,
      },
      {
        field: "Construction schedule",
        sourceTitle: "Synthetic schedule worksheet",
        sourceUrl: null,
        pageOrRow: `Fixture ${id}`,
        quote: start
          ? `Fictional construction window: ${start} through ${end} (end exclusive).`
          : "Construction dates have not been assigned to this fictional record.",
        synthetic: true,
      },
    ],
  };
}
export const projects: Project[] = [
  project(
    "P01",
    "lumen",
    "Lumen Electric",
    "Riverfront grid upgrade",
    "Electric distribution",
    -80.199,
    25.777,
    "2027-02-01",
    "2027-08-01",
  ),
  project(
    "P02",
    "tide",
    "Tide Waterworks",
    "Flagler water main",
    "Water infrastructure",
    -80.211,
    25.77,
    "2027-04-01",
    "2027-10-01",
  ),
  project(
    "P03",
    "ember",
    "Ember Fiber",
    "Civic district fiber loop",
    "Telecommunications",
    -80.19,
    25.79,
    "2027-06-01",
    "2027-11-01",
  ),
  project(
    "P04",
    "tide",
    "Tide Waterworks",
    "Southside pump renewal",
    "Water infrastructure",
    -80.214,
    25.753,
    "2028-01-01",
    "2028-05-01",
  ),
  project(
    "P05",
    "ember",
    "Ember Fiber",
    "West corridor expansion",
    "Telecommunications",
    -80.232,
    25.779,
    null,
    null,
  ),
  project(
    "P06",
    "tide",
    "Tide Waterworks",
    "Coastal resilience main",
    "Water infrastructure",
    -80.12,
    25.88,
    "2027-03-01",
    "2027-09-01",
  ),
  project(
    "P07",
    "lumen",
    "Lumen Electric",
    "Downtown feeder renewal",
    "Electric distribution",
    -80.195,
    25.774,
    "2027-03-01",
    "2027-07-01",
  ),
];
